openapi: 3.0.0
info:
  title: Customers
  version: '1.0'
  description: Chip
servers:
  - url: 'http://localhost:3000'
paths:
  /customers:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
      operationId: get-customers
      description: '12345678  '
  '/customers/{customer-id}':
    parameters:
      - schema:
          type: string
        name: customer-id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-customers-customer-id
      description: description 123
components:
  schemas: {}
